In [2]:
import sqlite3
import pandas as pd

con=sqlite3.connect(r'C:\Users\msham\OneDrive\Documents\OJT\Proj3.1\data\raw\2_IPL_Cricket\ipl.db')


def q(sql):
     return pd.read_sql(sql, con)

In [3]:
def run_sql_file(path):
    with open(path,'r') as f:
        script=f.read()
    con.executescript(script)
    con.commit()
    print('ran',path)

In [4]:
q("""
SELECT 
    batter,
    ROUND(
        100.0 * SUM(batter_runs) / SUM(
            CASE
                WHEN is_wide_ball = 0 AND is_no_ball = 0
                THEN 1
                ELSE 0
            END
        ), 2
    ) AS strike_rate
FROM deliveries
WHERE over_number BETWEEN 15 AND 19
  AND is_super_over = 0
GROUP BY batter
ORDER BY strike_rate DESC;
""")

             batter  strike_rate
0          WG Jacks       483.33
1          DT Patil       400.00
2        KT Maphaka       400.00
3            L Wood       300.00
4          PA Reddy       300.00
..              ...          ...
637     Sunny Gupta         0.00
638          U Kaul         0.00
639  V Pratap Singh         0.00
640   Y Prithvi Raj         0.00
641      YA Abdulla         0.00

[642 rows x 2 columns]

In [5]:
run_sql_file(r"C:\Users\msham\OneDrive\Documents\OJT\Proj3.1\Sql\Practice\09_analyisis_views.sql")

ran C:\Users\msham\OneDrive\Documents\OJT\Proj3.1\Sql\Practice\09_analyisis_views.sql

In [6]:
q("""SELECT *
FROM v_ball;""")

,season_id,match_id,batter,bowler,non_striker,over_number,ball_number,batter_runs,extras,total_runs,...,is_super_over,innings,batting_team_id,bowling_team_id,batting_team,bowling_team,phase,is_legal,bowler_runs,bowler_wicket
0,2008,335982,SC Ganguly,P Kumar,BB McCullum,0,0,0,1,1,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
1,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,1,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
2,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,2,0,1,1,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,0,1,0
3,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,3,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
4,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,4,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
288046,2026,1529286,T Stubbs,JC Archer,Ashutosh Sharma,18,3,1,0,1,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,1,0
288047,2026,1529286,Ashutosh Sharma,JC Archer,T Stubbs,18,4,1,0,1,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,1,0
288048,2026,1529286,T Stubbs,JC Archer,Ashutosh Sharma,18,5,4,0,4,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,4,0
288049,2026,1529286,Ashutosh Sharma,Brijesh Sharma,T Stubbs,19,0,4,0,4,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,4,0
288050,2026,1529286,Ashutosh Sharma,Brijesh Sharma,T Stubbs,19,1,0,1,1,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,0,1,0

In [7]:
q("""SELECT phase,COUNT(*) FROM v_ball GROUP BY phase;""")

       phase  COUNT(*)
0      Death     65488
1     Middle    132173
2  Powerplay     90390

In [8]:
q("""SELECT * FROM v_innings""")

,match_id,innings,batting_team,bowling_team,runs,wickets,legal_balls
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,222,3,120
1,335982,2,Royal Challengers Bangalore,Kolkata Knight Riders,82,10,91
2,335983,1,Chennai Super Kings,Punjab Kings,240,5,120
3,335983,2,Punjab Kings,Chennai Super Kings,207,4,120
4,335984,1,Rajasthan Royals,Delhi Capitals,129,8,120
...,...,...,...,...,...,...,...
2413,1529284,2,Sunrisers Hyderabad,Mumbai Indians,249,4,112
2414,1529285,1,Royal Challengers Bangalore,Gujarat Titans,155,10,116
2415,1529285,2,Gujarat Titans,Royal Challengers Bangalore,158,6,95
2416,1529286,1,Rajasthan Royals,Delhi Capitals,225,6,120
2417,1529286,2,Delhi Capitals,Rajasthan Royals,226,3,115

In [9]:
q("""SELECT * FROM v_match_totals; """)

,match_id,venue_clean,city_clean,season_year,result,match_winner,player_of_match,toss_winner,toss_decision,first_innings_runs,bat_first_team,chase_won
0,335982,M Chinnaswamy Stadium,Bangalore,2008,win,Kolkata Knight Riders,BB McCullum,Royal Challengers Bangalore,field,222,Kolkata Knight Riders,0
1,1082591,Rajiv Gandhi International Stadium,Hyderabad,2017,win,Sunrisers Hyderabad,Yuvraj Singh,Royal Challengers Bangalore,field,207,Sunrisers Hyderabad,0
2,1082592,Maharashtra Cricket Association Stadium,Pune,2017,win,Rising Pune Supergiant,SPD Smith,Rising Pune Supergiant,field,184,Mumbai Indians,1
3,1082593,Saurashtra Cricket Association Stadium,Rajkot,2017,win,Kolkata Knight Riders,CA Lynn,Kolkata Knight Riders,field,183,Gujarat Lions,1
4,1082594,Holkar Cricket Stadium,Indore,2017,win,Punjab Kings,GJ Maxwell,Punjab Kings,field,163,Rising Pune Supergiant,1
...,...,...,...,...,...,...,...,...,...,...,...,...
1182,1529282,Arun Jaitley Stadium,Delhi,2026,win,Royal Challengers Bangalore,JR Hazlewood,Royal Challengers Bangalore,field,75,Delhi Capitals,1
1183,1529283,Maharaja Yadavindra Singh International Cricke...,New Chandigarh,2026,win,Rajasthan Royals,D Ferreira,Rajasthan Royals,field,222,Punjab Kings,1
1184,1529284,Wankhede Stadium,Mumbai,2026,win,Sunrisers Hyderabad,H Klaasen,Mumbai Indians,bat,243,Mumbai Indians,1
1185,1529285,Narendra Modi Stadium,Ahmedabad,2026,win,Gujarat Titans,JO Holder,Gujarat Titans,field,155,Royal Challengers Bangalore,1
1186,1529286,Sawai Mansingh Stadium,Jaipur,2026,win,Delhi Capitals,KL Rahul,Rajasthan Royals,bat,225,Rajasthan Royals,1

In [10]:
q("""SELECT 
    batter,
    SUM(batter_runs) AS total_runs
FROM v_ball
GROUP BY batter
ORDER BY total_runs DESC
LIMIT 10;""")

           batter  total_runs
0         V Kohli        9040
1       RG Sharma        7183
2        S Dhawan        6769
3       DA Warner        6565
4        KL Rahul        5655
5        SK Raina        5528
6        MS Dhoni        5439
7       AM Rahane        5194
8  AB de Villiers        5162
9       SV Samson        5008

In [11]:
q("""SELECT batter,
             SUM(CASE WHEN batter_runs=6
        THEN 1 
        ELSE 0
        END) AS TOtal_sixes

FROM v_ball
GROUP BY batter
ORDER BY total_sixes DESC
limit 10;
 """)

           batter  TOtal_sixes
0        CH Gayle          357
1       RG Sharma          311
2         V Kohli          307
3        MS Dhoni          264
4  AB de Villiers          251
5       DA Warner          236
6       SV Samson          234
7        KL Rahul          232
8      AD Russell          223
9      KA Pollard          223

In [12]:
q("""SELECT batter, 

       SUM(is_legal) AS balls,

       SUM(batter_runs) AS runs,

       ROUND(100.0 * SUM(batter_runs),2) AS Boundary_perc

FROM v_ball
GROUP BY batter
HAVING runs>2000
ORDER BY Boundary_perc DESC 
LIMIT 10;""")

           batter  balls  runs  Boundary_perc
0         V Kohli   6730  9040       904000.0
1       RG Sharma   5396  7183       718300.0
2        S Dhawan   5302  6769       676900.0
3       DA Warner   4675  6565       656500.0
4        KL Rahul   4059  5655       565500.0
5        SK Raina   4022  5528       552800.0
6        MS Dhoni   3935  5439       543900.0
7       AM Rahane   4141  5194       519400.0
8  AB de Villiers   3392  5162       516200.0
9       SV Samson   3545  5008       500800.0

In [13]:
q("""SELECT batter,
       SUM(batter_runs) AS runs,
       ROUND(
           100.0 * SUM(
               CASE
                   WHEN batter_runs IN (4, 6)
                   THEN batter_runs
                   ELSE 0
               END
           ) / SUM(batter_runs),
           2
       ) AS Boundary_perc
FROM v_ball
GROUP BY batter
HAVING runs > 2000
ORDER BY Boundary_perc DESC
LIMIT 10;""")

            batter  runs  Boundary_perc
0       AD Russell  2651          78.54
1         CH Gayle  4965          75.77
2  Abhishek Sharma  2241          73.54
3      YBK Jaiswal  2478          73.28
4     AC Gilchrist  2069          72.89
5         V Sehwag  2728          72.29
6         N Pooran  2375          70.65
7         DR Smith  2385          70.52
8        SR Watson  3874          68.25
9       GJ Maxwell  2819          68.04

In [14]:
q(""" SELECT * FROM V_ball """)

,season_id,match_id,batter,bowler,non_striker,over_number,ball_number,batter_runs,extras,total_runs,...,is_super_over,innings,batting_team_id,bowling_team_id,batting_team,bowling_team,phase,is_legal,bowler_runs,bowler_wicket
0,2008,335982,SC Ganguly,P Kumar,BB McCullum,0,0,0,1,1,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
1,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,1,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
2,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,2,0,1,1,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,0,1,0
3,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,3,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
4,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,4,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
288046,2026,1529286,T Stubbs,JC Archer,Ashutosh Sharma,18,3,1,0,1,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,1,0
288047,2026,1529286,Ashutosh Sharma,JC Archer,T Stubbs,18,4,1,0,1,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,1,0
288048,2026,1529286,T Stubbs,JC Archer,Ashutosh Sharma,18,5,4,0,4,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,4,0
288049,2026,1529286,Ashutosh Sharma,Brijesh Sharma,T Stubbs,19,0,4,0,4,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,4,0
288050,2026,1529286,Ashutosh Sharma,Brijesh Sharma,T Stubbs,19,1,0,1,1,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,0,1,0

In [15]:
q("""SELECT batter,SUM(is_legal) AS balls,SUM(batter_runs) AS runs,
ROUND(100.0* SUM(batter_runs)/SUM(is_legal),2) AS run_rate

FROM v_ball
WHERE phase ='Middle'
GROUP BY batter
HAVING balls> 500
ORDER BY run_rate desc
LIMIT 20;
""")

             batter  balls  runs  run_rate
0          V Sehwag    611  1062    173.81
1        RM Patidar    566   970    171.38
2          N Pooran    848  1351    159.32
3         H Klaasen    697  1099    157.68
4          CH Gayle   1285  2011    156.50
5        AD Russell    767  1182    154.11
6         SR Watson   1302  2006    154.07
7        GJ Maxwell   1163  1780    153.05
8          SE Marsh    971  1448    149.12
9          DR Smith    675  1004    148.74
10  B Sai Sudharsan    694  1031    148.56
11       JC Buttler   1303  1890    145.05
12         SA Yadav   1845  2664    144.39
13     Shubman Gill   1300  1864    143.38
14       RD Gaikwad    780  1093    140.13
15       MA Agarwal    781  1094    140.08
16          VR Iyer    524   731    139.50
17      YBK Jaiswal    582   811    139.35
18     Ishan Kishan   1091  1518    139.14
19         KL Rahul   1740  2412    138.62

In [16]:
q("""
SELECT
    batter,
    SUM(batter_runs) AS total_runs,
    COUNT(*) AS balls_faced,
    ROUND(
        SUM(batter_runs) * 100.0 / COUNT(*), 2
    ) AS runs_rate
FROM deliveries
WHERE over_number BETWEEN 15 AND 19
GROUP BY batter
HAVING COUNT(*) >= 30
ORDER BY runs_rate DESC
LIMIT 10;
""")

            batter  total_runs  balls_faced  runs_rate
0          HM Amla         122           54     225.93
1        LJ Wright          84           38     221.05
2        BJ Rohrer          79           36     219.44
3         D Brevis          65           30     216.67
4   AB de Villiers        1868          867     215.46
5         V Sehwag          73           35     208.57
6       R Shepherd         168           81     207.41
7       MA Agarwal         252          124     203.23
8  B Sai Sudharsan         246          122     201.64
9         T Stubbs         533          265     201.13

In [17]:
q("""
SELECT 
    batter,
    SUM(batter_runs) AS runs,
    SUM(CASE WHEN is_legal = 1 THEN 1 ELSE 0 END) AS balls,
    ROUND(
        100.0 * SUM(batter_runs) /
        SUM(CASE WHEN is_legal = 1 THEN 1 ELSE 0 END),
        2
    ) AS strike_rate
FROM v_ball
WHERE phase = 'Powerplay'
GROUP BY batter
HAVING SUM(CASE WHEN is_legal = 1 THEN 1 ELSE 0 END) >= 100
ORDER BY strike_rate DESC
LIMIT 10;
""")

            batter  runs  balls  strike_rate
0    V Suryavanshi   467    202       231.19
1  J Fraser-McGurk   298    142       209.86
2    Priyansh Arya   603    301       200.33
3         A Mhatre   275    145       189.66
4          TM Head   884    493       179.31
5       P Nissanka   185    104       177.88
6          PD Salt   840    484       173.55
7  Abhishek Sharma  1287    744       172.98
8        SP Narine  1174    688       170.64
9      YBK Jaiswal  1579    984       160.47

who is the most reliable in a chase - strike  batting second

In [18]:
q(""" SELECT * FROM V_ball""")

,season_id,match_id,batter,bowler,non_striker,over_number,ball_number,batter_runs,extras,total_runs,...,is_super_over,innings,batting_team_id,bowling_team_id,batting_team,bowling_team,phase,is_legal,bowler_runs,bowler_wicket
0,2008,335982,SC Ganguly,P Kumar,BB McCullum,0,0,0,1,1,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
1,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,1,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
2,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,2,0,1,1,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,0,1,0
3,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,3,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
4,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,4,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
288046,2026,1529286,T Stubbs,JC Archer,Ashutosh Sharma,18,3,1,0,1,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,1,0
288047,2026,1529286,Ashutosh Sharma,JC Archer,T Stubbs,18,4,1,0,1,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,1,0
288048,2026,1529286,T Stubbs,JC Archer,Ashutosh Sharma,18,5,4,0,4,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,4,0
288049,2026,1529286,Ashutosh Sharma,Brijesh Sharma,T Stubbs,19,0,4,0,4,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,4,0
288050,2026,1529286,Ashutosh Sharma,Brijesh Sharma,T Stubbs,19,1,0,1,1,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,0,1,0

In [19]:
q(""" SELECT innings FROM V_ball""")

        innings
0             1
1             1
2             1
3             1
4             1
...         ...
288046        2
288047        2
288048        2
288049        2
288050        2

[288051 rows x 1 columns]

In [20]:
q("""
SELECT 
    batter,
    SUM(batter_runs) AS runs,
    SUM(CASE WHEN is_legal = 1 THEN 1 ELSE 0 END) AS balls,
    ROUND(
        100.0 * SUM(batter_runs) /
        SUM(CASE WHEN is_legal = 1 THEN 1 ELSE 0 END),
        2
    ) AS strike_rate
FROM v_ball
WHERE innings=2
GROUP BY batter
HAVING balls>500
ORDER BY strike_rate DESC
LIMIT 10;
""")

            batter  runs  balls  strike_rate
0        SP Narine   869    507       171.40
1       AD Russell  1130    660       171.21
2  Abhishek Sharma  1108    648       170.99
3         N Pooran  1218    729       167.08
4         V Sehwag  1427    869       164.21
5       GJ Maxwell  1164    734       158.58
6   P Simran Singh   832    527       157.87
7       JC Buttler  2289   1461       156.67
8      YBK Jaiswal  1351    875       154.40
9         SA Yadav  2131   1382       154.20

which batters are hardest to bowl a dot  in the death overs

In [21]:
q("""
SELECT
    batter,
    COUNT(*) AS balls_faced,
    SUM(CASE WHEN total_runs = 0 THEN 1 ELSE 0 END) AS dot_balls,
    ROUND(
        100.0 * SUM(CASE WHEN total_runs = 0 THEN 1 ELSE 0 END)
        / COUNT(*),
        2
    ) AS dot_ball_percentage
FROM v_ball
WHERE phase = 'Death'
  
GROUP BY batter
HAVING COUNT(*) > 100
ORDER BY dot_ball_percentage ASC
LIMIT 10;
""")

           batter  balls_faced  dot_balls  dot_ball_percentage
0       Q de Kock          123         18                14.63
1         C Green          130         20                15.38
2        T Stubbs          265         41                15.47
3        CL White          199         31                15.58
4   KS Williamson          287         45                15.68
5      MEK Hussey          138         23                16.67
6      MA Agarwal          124         21                16.94
7      AK Markram          165         28                16.97
8       JP Duminy          530         90                16.98
9  AB de Villiers          867        151                17.42

In [22]:
q("""SELECT batter,
        SUM(is_legal) AS balls,
        SUM(CASE WHEN 
            batter_runs=0 AND is_legal=1
            THEN 1 ELSE 0
            END) AS dot_balls,
        ROUND(100.0*SUM(CASE WHEN 
            batter_runs=0 AND is_legal=1
            THEN 1 ELSE 0
            END)/SUM(is_legal),2) AS
            dot_pct

FROM v_ball
WHERE phase='Death'
GROUP BY batter
HAVING balls >=500
ORDER BY dot_pct ASC
LIMIT 5;
""")

           batter  balls  dot_balls  dot_pct
0       JP Duminy    516        104    20.16
1  AB de Villiers    829        175    21.11
2        SK Raina    521        111    21.31
3        KL Rahul    502        110    21.91
4         V Kohli    807        185    22.92

In [23]:
q("""

SELECT phase,SUM(is_legal) AS balls,SUM(total_runs),
             ROUND(6.0*SUM(total_runs)/SUM(is_legal),2) AS runs_per_over,
             
             ROUND(100.0*SUM(is_wicket)/SUM(is_legal),2) AS wicket_perc

FROM v_ball
GROUP BY phase;



""")

       phase   balls  SUM(total_runs)  runs_per_over  wicket_perc
0      Death   62205           104056          10.04         8.46
1     Middle  128191           169160           7.92         4.34
2  Powerplay   86921           116397           8.03         4.01

In [24]:
q(""" 
 SELECT over_number+1 AS overs,
 ROUND(6.0*SUM(total_runs)/SUM(is_legal),2) AS runs_per_over
 FROM  v_ball
 GROUP BY over_number
 order BY runs_per_over DESC;

""")

    overs  runs_per_over
0      20          11.39
1      19          10.53
2      18          10.12
3      17           9.46
4      16           9.05
5      15           8.74
6       6           8.68
7       5           8.65
8       4           8.63
9      14           8.43
10      3           8.37
11     13           8.17
12     12           8.13
13     11           7.96
14      9           7.77
15     10           7.66
16      2           7.60
17      8           7.47
18      7           6.98
19      1           6.28

In [25]:
q("""
SELECT ROUND(AVG(pp_runs),2) AS avg_powerplay_Score

FROM (SELECT match_id,innings,SUM(total_runs) AS pp_runs
    FROM v_ball
    WHERE phase='Powerplay' AND innings IN(1,2)
    GROUP BY match_id,innings);
""" )

   avg_powerplay_Score
0                48.14

In [26]:
q("""
SELECT
    over_number + 1 AS over,
    SUM(is_wicket) AS wickets
FROM v_ball
GROUP BY over_number
ORDER BY over_number DESC;
""")

    over  wickets
0     20     1433
1     19     1089
2     18     1055
3     17      863
4     16      824
5     15      764
6     14      703
7     13      661
8     12      621
9     11      635
10    10      554
11     9      593
12     8      534
13     7      497
14     6      585
15     5      640
16     4      597
17     3      606
18     2      567
19     1      488

In [27]:
q("""
SELECT bowler,SUM(bowler_wicket) AS wicket 
FROM v_ball
GROUP BY bowler
ORDER BY wicket DESC;
""")

               bowler  wicket
0           YS Chahal     228
1             B Kumar     215
2           SP Narine     199
3           PP Chawla     192
4            R Ashwin     187
..                ...     ...
563       Tilak Varma       0
564       VS Yeligati       0
565    Vivrant Sharma       0
566  Y Gnaneswara Rao       0
567       YBK Jaiswal       0

[568 rows x 2 columns]

In [28]:
q("""
SELECT 
    bowler,
    COUNT(*) AS legal_balls,
    SUM(total_runs) AS runs_conceded,
    ROUND(6.0 * SUM(total_runs) / COUNT(*), 2) AS economy
FROM v_ball
WHERE is_wide_ball = 0 
  AND is_no_ball = 0
GROUP BY bowler
HAVING COUNT(*) >= 500
ORDER BY economy ASC
LIMIT 10;
""")

            bowler  legal_balls  runs_conceded  economy
0         A Kumble          965           1050     6.53
1   M Muralitharan         1524           1690     6.65
2         DW Steyn         2176           2438     6.72
3        SP Narine         4507           5103     6.79
4       DL Vettori          777            886     6.84
5          J Botha          694            799     6.91
6       SL Malinga         2827           3291     6.98
7  Harbhajan Singh         3416           3996     7.02
8         R Ashwin         4710           5521     7.03
9         R Sharma          928           1093     7.07

In [29]:
q(""" 
SELECT bowler,SUM(is_legal) AS total_balls,SUM(bowler_wicket) AS total_wicket,

              ROUND(1.0*SUM(is_legal)/SUM(bowler_wicket),2) AS balls_per_wicket

FROM v_ball
GROUP BY bowler 
having total_wicket>50
ORDER BY balls_per_wicket;


""")

          bowler  total_balls  total_wicket  balls_per_wicket
0     AD Russell         1806           123             14.68
1   JR Hazlewood         1008            65             15.51
2       K Rabada         2112           133             15.88
3       MA Starc         1083            68             15.93
4    Imran Tahir         1316            82             16.05
..           ...          ...           ...               ...
73      I Sharma         2419            96             25.20
74     IK Pathan         2043            80             25.54
75      AR Patel         3483           136             25.61
76     JH Kallis         1742            65             26.80
77       P Kumar         2524            90             28.04

[78 rows x 4 columns]

In [30]:
q("""
SELECT
    bowler,
    SUM(is_legal) AS balls,
    SUM(CASE WHEN batter_runs IN (4, 6) THEN 1 ELSE 0 END) AS boundaries,
    ROUND(
        100.0 * SUM(CASE WHEN batter_runs IN (4, 6) THEN 1 ELSE 0 END)
        / SUM(is_legal),
        2
    ) AS boundary_perc
FROM v_ball
GROUP BY bowler
HAVING SUM(is_legal) >= 1000
ORDER BY boundary_perc ASC
LIMIT 10;
""")

            bowler  balls  boundaries  boundary_perc
0   M Muralitharan   1524         170          11.15
1         R Bhatia   1636         188          11.49
2        SP Narine   4507         526          11.67
3         R Ashwin   4710         555          11.78
4         M Kartik   1149         138          12.01
5         SK Warne   1194         147          12.31
6         A Mishra   3371         423          12.55
7          PP Ojha   1899         243          12.80
8      Rashid Khan   3387         436          12.87
9  Harbhajan Singh   3416         441          12.91

In [31]:
q("""

SELECT bowler,SUM(is_legal) AS balls,SUM(CASE WHEN total_runs=0 AND is_legal=1
                                THEN 1
                                ELSE 0
                                END) AS dot_balls,
                            ROUND(100.0*SUM(CASE WHEN total_runs=0 AND is_legal=1
                            THEN 1
                            ELSE 0
                            END)/SUM(is_legal),2) AS dot_perc 
                            
FROM v_ball
GROUP BY bowler
HAVING balls >=1000
ORDER BY dot_perc DESC
LIMIT 10;
""")

         bowler  balls  dot_balls  dot_perc
0      DW Steyn   2176       1019     46.83
1     JC Archer   1440        627     43.54
2      MM Patel   1355        590     43.54
3      M Morkel   1629        708     43.46
4    MG Johnson   1232        533     43.26
5  JR Hazlewood   1008        434     43.06
6       P Kumar   2524       1075     42.59
7     DL Chahar   1954        827     42.32
8      RP Singh   1775        744     41.92
9       A Nehra   1908        798     41.82

In [32]:
q("""

SELECT wicket_kind,COUNT(*) AS n
FROM v_ball 
WHERE is_wicket=1
GROUP BY wicket_kind
ORDER BY n DESC
;
""")

             wicket_kind     n
0                 caught  9045
1                 bowled  2398
2                run out  1167
3                    lbw   871
4      caught and bowled   399
5                stumped   382
6           retired hurt    19
7             hit wicket    18
8            retired out     6
9  obstructing the field     4

In [33]:
q("""SELECT CASE WHEN bowler_type LIKE                       
       '%Legbreak%' OR bowler_type LIKE 
       '%Offbreak%' OR bowler_type LIKE 
       '%Orthodox%' OR bowler_type LIKE 
       '%Wrist spin%' OR bowler_type LIKE 
       '%Googly%' THEN 'Spin' ELSE 'Pace' 
       END AS style,                                    -- branches of th 
       SUM(is_legal) AS balls,                          -- sample size 
       ROUND(6.0*SUM(bowler_runs)/SUM(is_legal),2)      -- runs per over 
              AS economy, 
       ROUND(100.0*SUM(bowler_wicket)/SUM(is_legal),2)  
              AS wicket_pct 
FROM   v_ball                                           -- one row = one 
WHERE  bowler_type IS NOT NULL AND                      -- drop the blanks 
       TRIM(bowler_type) <> '' 
GROUP  BY style;                                        -- one row per gr

""")

  style   balls  economy  wicket_pct
0  Pace  176859     8.57        4.93
1  Spin  100129     7.76        4.37

In [34]:
q("""
SELECT
    CASE
        WHEN bowler_type LIKE 'Left%'
        THEN 'Left arm'
        ELSE 'Right arm'
    END AS arm,

    batsman_type,

    ROUND(
        6.0 * SUM(bowler_runs) / SUM(is_legal),
        2
    ) AS economy,

    ROUND(
        100.0 * SUM(bowler_wicket) / SUM(is_legal),
        2
    ) AS wicket_pct

FROM v_ball

WHERE TRIM(COALESCE(bowler_type, '')) <> ''
  AND batsman_type IS NOT NULL

GROUP BY arm, batsman_type;
""")

         arm    batsman_type  economy  wicket_pct
0   Left arm   Left hand Bat     8.81        5.13
1   Left arm  Right hand Bat     8.49        4.97
2  Right arm   Left hand Bat     8.33        4.46
3  Right arm  Right hand Bat     8.16        4.78

In [35]:
q("""
SELECT
    bowler,
    SUM(bowler_wicket) AS wicket,
    ROUND(
        100.0 * SUM(bowler_wicket) / SUM(is_legal),
        2
    ) AS wicket_perc
FROM v_ball
WHERE bowler_type LIKE '%Legbreak%'
   OR bowler_type LIKE '%Offbreak%'
   OR bowler_type LIKE '%Orthodox%'
   OR bowler_type LIKE '%Wrist spin%'
   OR bowler_type LIKE '%Googly%'
GROUP BY bowler
HAVING SUM(is_legal) >= 1000
ORDER BY wicket DESC
LIMIT 10;
""")

            bowler  wicket  wicket_perc
0        YS Chahal     228         5.79
1        SP Narine     199         4.42
2        PP Chawla     192         4.99
3         R Ashwin     187         3.97
4        RA Jadeja     177         4.23
5         A Mishra     174         5.16
6      Rashid Khan     168         4.96
7  Harbhajan Singh     150         4.39
8         AR Patel     136         3.90
9    Kuldeep Yadav     109         4.90

In [36]:
q("""
SELECT
    bowler,
    SUM(is_legal) AS balls,
    SUM(bowler_runs) AS bowler_runs,
    ROUND(6.0 * SUM(bowler_runs) / SUM(is_legal), 2) AS economy
FROM v_ball
WHERE over_number BETWEEN 15 AND 19
GROUP BY bowler
HAVING SUM(is_legal) >=300
ORDER BY economy ASC
LIMIT 10;
""")

        bowler  balls  bowler_runs  economy
0    SP Narine   1075         1307     7.29
1   SL Malinga   1117         1464     7.86
2    JJ Bumrah   1393         1911     8.23
3     R Ashwin    601          825     8.24
4     DW Steyn    634          877     8.30
5     CV Varun    310          432     8.36
6  Rashid Khan    594          829     8.37
7     AR Patel    376          539     8.60
8    PP Chawla    444          641     8.66
9    CH Morris    646          933     8.67

In [37]:
q("""
SELECT
    bowler,
    SUM(is_legal) AS balls,
    SUM(bowler_wicket) AS wickets,
    ROUND(100.0 * SUM(bowler_wicket) / SUM(is_legal), 2) AS wicket_perc
    FROM v_ball
    WHERE over_number BETWEEN 0 AND 5
    GROUP BY bowler
    HAVING balls > 300
    ORDER BY wickets DESC
    LIMIT 10;
    """)

           bowler  balls  wickets  wicket_perc
0         B Kumar   2453       89         3.63
1        TA Boult   1644       72         4.38
2       DL Chahar   1527       67         4.39
3  Sandeep Sharma   1728       64         3.70
4        UT Yadav   1446       58         4.01
5        I Sharma   1521       57         3.75
6  Mohammed Shami   1584       57         3.60
7          Z Khan   1292       52         4.02
8  Mohammed Siraj   1326       50         3.77
9        R Ashwin   1252       50         3.99

In [38]:
q("""
SELECT
    bowler,
    SUM(is_legal) AS balls,
    SUM(is_legal AND total_runs = 0) AS dot_balls,
    ROUND(100.0 * SUM(is_legal AND total_runs = 0) / SUM(is_legal), 2) AS dot_perc
FROM v_ball
WHERE phase = 'Death'
GROUP BY bowler
HAVING balls >= 300
ORDER BY dot_perc DESC
LIMIT 10;
""")

              bowler  balls  dot_balls  dot_perc
0          SP Narine   1075        397     36.93
1           CV Varun    310        112     36.13
2         MG Johnson    302        108     35.76
3        Rashid Khan    594        208     35.02
4           DW Steyn    634        218     34.38
5          PP Chawla    444        150     33.78
6           K Rabada    660        222     33.64
7  M Prasidh Krishna    542        182     33.58
8           A Mishra    521        167     32.05
9           MA Starc    333        106     31.83

In [39]:
run_sql_file(r"C:\Users\msham\OneDrive\Documents\OJT\Proj3.1\Sql\Practice\08_matches_clean.sql")

ran C:\Users\msham\OneDrive\Documents\OJT\Proj3.1\Sql\Practice\08_matches_clean.sql

In [40]:
q("""
SELECT
    COUNT(*) AS decisive_matches,

    SUM(
        CASE
            WHEN toss_winner = match_winner THEN 1
            ELSE 0
        END
    ) AS toss_winner_won,

    ROUND(
        100.0 * SUM(
            CASE
                WHEN toss_winner = match_winner THEN 1
                ELSE 0
            END
        ) / COUNT(*),
        2
    ) AS pct

FROM matches_clean
WHERE result = 'win';
""")

   decisive_matches  toss_winner_won    pct
0              1187              613  51.64

In [41]:
q("""
SELECT
    LOWER(toss_decision) AS decision,
    COUNT(*) AS total_tosses,
    ROUND(100.0 * COUNT(*) / (SELECT COUNT(*) FROM matches_clean), 2) AS pct
FROM matches_clean
GROUP BY LOWER(toss_decision);
""")

  decision  total_tosses    pct
0      bat           412  33.99
1    field           800  66.01

In [42]:
q("""SELECT COUNT(*) FROM matches;  """)

   COUNT(*)
0      1212

In [43]:
q("""
SELECT
    toss_winner,
    COUNT(*) AS toss_won
FROM matches_clean
GROUP BY toss_winner
ORDER BY toss_won DESC;
""")

                    toss_winner  toss_won
0                Mumbai Indians       156
1                Delhi Capitals       145
2           Sunrisers Hyderabad       139
3              Rajasthan Royals       134
4   Royal Challengers Bangalore       132
5         Kolkata Knight Riders       132
6           Chennai Super Kings       130
7                  Punjab Kings       126
8                Gujarat Titans        33
9          Lucknow Super Giants        29
10                Pune Warriors        20
11                Gujarat Lions        15
12       Rising Pune Supergiant        13
13         Kochi Tuskers Kerala         8

In [44]:
q("""
SELECT ROUND(AVG(first_innings_runs), 2) AS average_first_innings_score
FROM v_match_totals;
""")

   average_first_innings_score
0                       168.19

In [45]:
q("""
SELECT
    innings,
    ROUND(6.0 * SUM(total_runs) / SUM(is_legal), 2) AS run_rate
FROM v_ball
WHERE innings IN (1, 2)
GROUP BY innings
ORDER BY innings;
""")

   innings  run_rate
0        1      8.49
1        2      8.37

In [46]:
q("""
SELECT
    CASE innings
        WHEN 1 THEN 'Batting first'
        WHEN 2 THEN 'Batting second'
    END AS batting_order,
    ROUND(AVG(wickets), 2) AS average_wickets_lost
FROM v_innings
GROUP BY innings
ORDER BY average_wickets_lost DESC;
""")

    batting_order  average_wickets_lost
0   Batting first                  6.13
1  Batting second                  5.70

In [47]:
q("""
SELECT
    COUNT(*) AS match_with_200plus,
    SUM(chase_won) AS successfully_chased 

    FROM v_match_totals
    WHERE first_innings_runs >=200;
    
""")

   match_with_200plus  successfully_chased
0                 198                   46

In [48]:
q("""
SELECT
    MAX(CASE WHEN chase_won = 0 THEN first_innings_runs END) AS biggest_defend,
    MAX(CASE WHEN chase_won = 1 THEN first_innings_runs END) AS biggest_chased
FROM v_match_totals;
""")

   biggest_defend  biggest_chased
0             287             264

In [49]:
q("""
SELECT
    venue_clean AS ground,
    COUNT(*) AS matches_hosted
FROM matches_clean
WHERE venue_clean IS NOT NULL
  AND TRIM(venue_clean) <> ''
GROUP BY venue_clean
ORDER BY matches_hosted DESC
LIMIT 10;
""")

                                ground  matches_hosted
0                     Wankhede Stadium             130
1                M Chinnaswamy Stadium             104
2                         Eden Gardens             104
3               MA Chidambaram Stadium              95
4   Rajiv Gandhi International Stadium              87
5               Sawai Mansingh Stadium              66
6                     Feroz Shah Kotla              60
7  Dubai International Cricket Stadium              46
8                 Arun Jaitley Stadium              41
9                Narendra Modi Stadium              37

In [50]:
q("""SELECT m.venue_clean,
       COUNT(DISTINCT m.match_id) AS matches,
       ROUND(AVG(i.runs), 2) AS avg_score
FROM matches_clean m
JOIN v_innings i ON i.match_id = m.match_id
GROUP BY m.venue_clean
HAVING matches >= 25
ORDER BY avg_score DESC
LIMIT 10;
""")

                                         venue_clean  matches  avg_score
0                               Arun Jaitley Stadium       41     180.04
1                              Narendra Modi Stadium       37     177.82
2                                  Brabourne Stadium       27     172.31
3       Punjab Cricket Association IS Bindra Stadium       26     170.71
4  Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...       26     167.59
5                                   Wankhede Stadium      130     166.95
6                              M Chinnaswamy Stadium      104     165.67
7                             Sawai Mansingh Stadium       66     161.11
8                 Rajiv Gandhi International Stadium       87     161.06
9                                       Eden Gardens      104     160.94

In [51]:
q("""
SELECT
    match_winner AS team,
    COUNT(*) AS wins
FROM matches_clean
WHERE RESULT='win'
GROUP BY match_winner
ORDER BY wins DESC
LIMIT 10;
""")

                          team  wins
0               Mumbai Indians   153
1          Chennai Super Kings   145
2  Royal Challengers Bangalore   138
3        Kolkata Knight Riders   136
4          Sunrisers Hyderabad   128
5                 Punjab Kings   125
6               Delhi Capitals   122
7             Rajasthan Royals   120
8               Gujarat Titans    42
9         Lucknow Super Giants    32

In [52]:
q("""
SELECT
    batting_team,
    SUM(is_legal) AS legal_balls,
    SUM(total_runs) AS runs,
    ROUND(6.0 * SUM(total_runs) / SUM(is_legal), 2) AS run_rate
FROM v_ball
WHERE phase = 'Powerplay'
GROUP BY batting_team
HAVING SUM(is_legal) >= 3000
ORDER BY run_rate DESC
LIMIT 10;
""")

                  batting_team  legal_balls   runs  run_rate
0                 Punjab Kings         9755  13344      8.21
1          Sunrisers Hyderabad        10034  13712      8.20
2             Rajasthan Royals         8768  11797      8.07
3               Delhi Capitals         9893  13237      8.03
4        Kolkata Knight Riders         9738  13016      8.02
5               Mumbai Indians        10257  13561      7.93
6  Royal Challengers Bangalore        10008  13196      7.91
7          Chennai Super Kings         9324  12198      7.85

In [53]:
q("""
SELECT
    batting_team AS team,
    SUM(CASE WHEN batter_runs IN (4, 6) THEN batter_runs ELSE 0 END) AS boundary_runs,
    SUM(total_runs) AS total_runs,
    ROUND(
        100.0 * SUM(CASE WHEN batter_runs IN (4, 6) THEN batter_runs ELSE 0 END)
        / SUM(batter_runs), 2
    ) AS boundary_percentage
FROM v_ball
GROUP BY batting_team
HAVING SUM(is_legal) >=10000
ORDER BY boundary_percentage DESC
LIMIT 10;
""")

                          team  boundary_runs  total_runs  boundary_percentage
0               Mumbai Indians          27486       46517                62.30
1        Kolkata Knight Riders          24846       42540                61.84
2                 Punjab Kings          25986       44352                61.67
3  Royal Challengers Bangalore          26220       44890                61.44
4             Rajasthan Royals          22718       39159                60.90
5               Delhi Capitals          24688       43297                59.97
6          Chennai Super Kings          24186       42557                59.80
7          Sunrisers Hyderabad          24982       44948                58.50

In [54]:
q("""
SELECT batting_team,
       ROUND(
           100.0 * SUM(
               CASE
                   WHEN batter_runs IN (4,6)
                   THEN batter_runs
                   ELSE 0
               END
           ) / SUM(batter_runs), 2
       ) AS boundary_perc
FROM v_ball
GROUP BY batting_team
HAVING SUM(is_legal) >= 10000
ORDER BY boundary_perc DESC
LIMIT 10;
""")

                  batting_team  boundary_perc
0               Mumbai Indians          62.30
1        Kolkata Knight Riders          61.84
2                 Punjab Kings          61.67
3  Royal Challengers Bangalore          61.44
4             Rajasthan Royals          60.90
5               Delhi Capitals          59.97
6          Chennai Super Kings          59.80
7          Sunrisers Hyderabad          58.50

In [55]:


q("""
SELECT player_of_match AS player,
    COUNT(*) AS award_count
FROM matches_clean
WHERE player_of_match IS NOT NULL
GROUP BY player_of_match
ORDER BY award_count DESC
LIMIT 10;
""")

           player  award_count
0  AB de Villiers           25
1        CH Gayle           22
2       RG Sharma           21
3         V Kohli           20
4        MS Dhoni           18
5       DA Warner           18
6       SP Narine           17
7       RA Jadeja           17
8        KL Rahul           17
9       YK Pathan           16

In [56]:
q("""
SELECT
    phase,
    wicket_kind,
    COUNT(*) AS N,
    ROUND(
        100.0 * COUNT(*) /
        SUM(COUNT(*)) OVER (PARTITION BY phase),
        2
    ) AS percentage
FROM v_ball
WHERE is_wicket = 1
  AND wicket_kind IN ('caught', 'bowled', 'run out')
GROUP BY phase, wicket_kind
ORDER BY phase,N DESC;
""")

       phase wicket_kind     N  percentage
0      Death      caught  3289       68.52
1      Death      bowled   877       18.27
2      Death     run out   634       13.21
3     Middle      caught  3484       73.55
4     Middle      bowled   909       19.19
5     Middle     run out   344        7.26
6  Powerplay      caught  2272       73.93
7  Powerplay      bowled   612       19.92
8  Powerplay     run out   189        6.15

In [57]:
q("""
SELECT
    batter AS player_out,
    COUNT(*) AS runout_count
FROM v_ball
WHERE wicket_kind='run out'
GROUP BY player_out
ORDER BY runout_count DESC
LIMIT 10;
""")

        player_out  runout_count
0         S Dhawan            16
1        R Tewatia            16
2         SK Raina            15
3     Basil Thampi            15
4        AT Rayudu            15
5    Mandeep Singh            14
6          M Vijay            12
7     F du Plessis            12
8        YK Pathan            11
9  Y Venugopal Rao            11

In [58]:
q("""
SELECT
    season_year,
    COUNT(*) AS matches_played
FROM matches_clean
GROUP BY season_year
ORDER BY season_year;
""")

    season_year  matches_played
0          2008              58
1          2009              57
2          2010              60
3          2011              73
4          2012              74
5          2013              76
6          2014              60
7          2015              59
8          2016              60
9          2017              59
10         2018              60
11         2019              60
12         2020              60
13         2021              60
14         2022              74
15         2023              74
16         2024              71
17         2025              74
18         2026              43

In [59]:
q("""
SELECT
    bowler,
    COUNT(*) AS times_dismissed
FROM v_ball
WHERE batter = 'V Kohli'
 AND bowler_wicket = 1
GROUP BY bowler
ORDER BY times_dismissed DESC;
""")

             bowler  times_dismissed
0    Sandeep Sharma                7
1           A Nehra                6
2    Mohammed Shami                5
3         JJ Bumrah                5
4         SP Narine                4
..              ...              ...
127      AD Mathews                1
128       AC Thomas                1
129       A Symonds                1
130        A Nortje                1
131        A Kamboj                1

[132 rows x 2 columns]

In [60]:
q("""
SELECT
    bowler,batter,
    COUNT(*) AS times_out
FROM v_ball
WHERE bowler_wicket=1
GROUP BY bowler,batter
ORDER BY times_out DESC;
""")

               bowler           batter  times_out
0           SP Narine        RG Sharma          8
1            A Mishra        RG Sharma          7
2             B Kumar        AM Rahane          7
3           JJ Bumrah          RR Pant          7
4           MM Sharma        AT Rayudu          7
...               ...              ...        ...
10305  Zeeshan Ansari  B Sai Sudharsan          1
10306  Zeeshan Ansari     F du Plessis          1
10307  Zeeshan Ansari  J Fraser-McGurk          1
10308  Zeeshan Ansari         KL Rahul          1
10309  Zeeshan Ansari         WG Jacks          1

[10310 rows x 3 columns]

In [61]:
q("""
SELECT 
    batter,
    SUM(is_legal) AS balls,
    SUM(batter_runs) AS runs,
    ROUND(
        100.0 * SUM(batter_runs) / SUM(is_legal),
        2
    ) AS sr
FROM v_ball
WHERE phase = 'Powerplay' 
  AND is_wicket = 0
GROUP BY batter
HAVING balls >= 500
ORDER BY sr DESC;
""")

             batter  balls  runs      sr
0         SP Narine    640  1174  183.44
1   Abhishek Sharma    712  1287  180.76
2       YBK Jaiswal    948  1579  166.56
3    P Simran Singh    658  1070  162.61
4       JM Bairstow    601   944  157.07
5           PP Shaw    866  1347  155.54
6          V Sehwag   1036  1593  153.76
7           CA Lynn    520   779  149.81
8       RA Tripathi    685  1013  147.88
9        JC Buttler   1216  1788  147.04
10         SA Yadav    685   984  143.65
11        DA Warner   2312  3316  143.43
12     AC Gilchrist    978  1384  141.51
13  B Sai Sudharsan    597   844  141.37
14     Ishan Kishan   1015  1432  141.08
15     F du Plessis   1617  2281  141.06
16         CH Gayle   1689  2373  140.50
17          WP Saha    990  1389  140.30
18         SK Raina   1117  1552  138.94
19     Shubman Gill   1378  1912  138.75
20       D Padikkal    704   964  136.93
21        Q de Kock   1445  1963  135.85
22      BB McCullum   1155  1555  134.63
23          M Vohra    514   689  134.05
24        RG Sharma   1874  2479  132.28
25          V Kohli   2527  3339  132.13
26        SV Samson   1149  1518  132.11
27       RD Gaikwad    984  1298  131.91
28         KL Rahul   1777  2336  131.46
29       RV Uthappa   1566  2035  129.95
30       MA Agarwal   1092  1409  129.03
31         DR Smith    943  1213  128.63
32         PA Patel   1485  1903  128.15
33         S Dhawan   2674  3415  127.71
34        AM Rahane   2078  2647  127.38
35        G Gambhir   1795  2275  126.74
36           N Rana    632   799  126.42
37   AB de Villiers    584   722  123.63
38    Mandeep Singh    519   633  121.97
39         AJ Finch    747   909  121.69
40     SR Tendulkar    951  1143  120.19
41          M Vijay   1323  1572  118.82
42        MK Pandey    954  1124  117.82
43          SS Iyer    840   987  117.50
44        SR Watson   1213  1415  116.65
45         R Dravid    811   905  111.59
46       MEK Hussey    747   828  110.84
47        JH Kallis    938  1036  110.45
48        AT Rayudu    705   777  110.21
49         SE Marsh    709   767  108.18

In [62]:
q(""" 

SELECT b.batter AS players,
     SUM(b.batter_runs) AS runs,
     (SELECT SUM(X.bowler_wicket) FROM v_ball AS x
     WHERE x.bowler=b.batter)AS wickets

    FROM v_ball b
    GROUP BY b.batter
HAVING runs>=1000 AND wickets>=50
    ORDER BY runs DESC
    LIMIT 10;""")

      players  runs  wickets
0   SR Watson  3874       92
1  KA Pollard  3412       69
2   RA Jadeja  3412      177
3   HH Pandya  2877       82
4  AD Russell  2651      123
5   JH Kallis  2427       65
6    AR Patel  1947      136
7   SP Narine  1820      199
8   KH Pandya  1796      102
9    DJ Bravo  1560      183

In [63]:
q("""
select batter,
sum(is_legal) as balls,
round(100.0*sum(batter_runs)/sum(is_legal),2) as sr
from v_ball
where innings=2 and phase='Death'
group by batter
having balls>=200
order by sr desc
limit 10;
""")

           batter  balls      sr
0  AB de Villiers    295  209.83
1         SS Iyer    215  187.44
2       DA Miller    439  186.33
3         RR Pant    214  185.51
4       SV Samson    207  183.57
5      KA Pollard    429  183.45
6      SO Hetmyer    217  180.65
7         V Kohli    336  180.65
8      AD Russell    265  174.72
9       YK Pathan    331  174.32